### ISSUE TITLE
Vim 7.4.565+ throws E16 for `0wincmd w`

### ISSUE THREAD

**Issue by lesguillemets** [t9md/vim-quickhl#11]
Recent version of vim throws `E16: Invalid range` for `0wincmd w`. quickhl is affected when `winnr('#')` is 0, with `quickhl#windo` having `execute pwinnum . "wincmd w"` in its body.

I believe this change was introduced in patch [7.4.565](http://ftp.vim.org/vim/patches/7.4/7.4.565). At least vim 7.4.560 is not affected, and I confirmed this error in vim 7.4.567.

**Comment by t9md** [comment]
Thanks for report and your investigation.
I will look to this.

**Comment by t9md** [comment]
I'm not sure my fix is appropriate. simply avoid winced when 0 is returned from `winner()`.
Thank you for your investigation.

**Comment by lesguillemets** [comment]
Thank you for the quick response! The problem I reported here is no longer reproductive. I think this can be considered to be fixed, unless this change is unexpectedly  observed to introduce some other misbehaviours.

Looking at #5 , `pwinnum` seems to have been introduced solely for restoring "the previous window", and as far as I can tell, this commit does not impair its functionality. +1 .

By the way, thank you very much for the plugin: it is really life-changing.

**Comment by t9md** [comment]
Year. As you wrote, I'm sure this fix won't break basic behavior thus nor risk and its should be OK.
Thank you for your positive feedback , its very encouraging for me!!

**Comment by lesguillemets** [comment]
It's been quite a while since the fix and no side effects have been reported. I believe it's now safe to close this issue even if you intentionally left it open. Thank you very much!
