### ISSUE TITLE
"E15: Invalid expression" happens at quickhl-manual-this and quickhl-manual-this-whole-word

### ISSUE THREAD

**Issue by msfm** [t9md/vim-quickhl#21]
The following error happens when executing `quickhl-manual-this` on Vim 7.4.160 which is default package provided by RHEL 7: 

~~~
Error detected while processing function quickhl#manual#this..quickhl#manual#add_or_del:
line    3:
E109: Missing ':' after '?'
E116: Invalid arguments for function 26
E15: Invalid expression: s:manual.index_of(a:escaped?a:pattern:quickhl#escape(a:pattern)) == -1
~~~

Also, the following error happens when executing `quickhl-manual-this-whole-word`:

~~~
Error detected while processing function quickhl#manual#this_whole_word..quickhl#manual#add_or_del:
line    3:
E117: Unknown function: a:pattern:quickhl#escape
E116: Invalid arguments for function 26
E15: Invalid expression: s:manual.index_of(a:escaped?a:pattern:quickhl#escape(a:pattern)) == -1
~~~

It looks the commit https://github.com/t9md/vim-quickhl/commit/3ca1252bc2caf49047c07e21d3a4e09816a8013f added the following ternary operator (`?:`) in the `quickhl#manual#add_or_del` function and this causes this issue:

~~~
if s:manual.index_of(a:escaped?a:pattern:quickhl#escape(a:pattern)) == -1
~~~

Actually this should be:

~~~
if s:manual.index_of(a:escaped ? a:pattern : quickhl#escape(a:pattern)) == -1
~~~

Note: this error does not happen when I try it on Vim 8.0.1171 provided by Fedora 26, so I guess the newer version of Vim has some improvement for parsing the ternary operator. However, a plugin would be better to use a compatible notation to the previous versions.

**Comment by t9md** [comment]
Thanks!!
