### ISSUE TITLE
Suggest adding "cterm=bold" in g:quickhl_manual_colors

### ISSUE THREAD

**Issue by adonis0147** [t9md/vim-quickhl#23]
I spot that the current color scheme is not obvious in terminal, so I suggest adding `cterm=bold` in  g:quickhl_manual_colors as default options like the options in gui.

current appearance in terminal:
<img width="798" alt="wx20171014-131144 2x" src="https://user-images.githubusercontent.com/1443003/31572845-af536a7a-b074-11e7-8aa4-b335e9d144b1.png">
It is hard to recognize the words in QuickhlManual3, QuickhlManual9 and QuickhlManual11.

**Comment by t9md** [comment]
I'll wait for PR from you.
