### ISSUE TITLE
set completeopt+=popup and complete work,Error happen.

### ISSUE THREAD

**Issue by tsuyoshicho** [t9md/vim-quickhl#27]
## setting

vim work with asyncomplete
set `set completeopt+=popup`

start edit and completion happen.

complete item select

## message
```
 Error detected while processing function quickhl#manual#refresh[1]..quickhl#windo:
line    6:
E994: Not allowed in a popup window
```

https://github.com/t9md/vim-quickhl/blob/c6031afb874cea4fb7796be6a120624d0e073d65/autoload/quickhl.vim#L28-L40

**Comment by tsuyoshicho** [comment]
windo work to popup buffer and error?

**Comment by t9md** [comment]
Thanks for reporting. It seems clearly quick-hl's bug.
It should be able to fix by detecting a popup window and ignore it.
If someone can fix it, I really appreciate it. I have not much time to work on this in the next 1.5 months.

**Comment by t9md** [comment]
I believe the above commit fix your issue.
I am not an active vim user now and I do not use an async complete popup, so I could not reproduce your issue in my setup.

My fix is technically read manual and theoretically applied what I believe I can fix.

Please give feedback to me when you tried.

**Comment by t9md** [comment]
I noticed my misunderstanding for window-ID, so the above code does not fix your issue.
Let me find proper way.

**Comment by t9md** [comment]
I believe this is it!
Please give feedback when you tried.

**Comment by tsuyoshicho** [comment]
Thanks a lot.
try it

**Comment by tsuyoshicho** [comment]
I try it.

result:
Error happen.
message as same.

(note: Currently completion work vim-clang)

**Comment by tsuyoshicho** [comment]
I re-try it.

 error occur.

---

I think execute in normal(not popup) window,  `win_execute` is usable?
 see https://vim-jp.org/vimdoc-ja/eval.html#win_execute()

**Comment by tsuyoshicho** [comment]
3rd try it.

It OK, do not happen error E994 and popup appear.
